[tool.poetry]
name = "ecb-forex-rates"
version = "0.1.0"
description = ""
authors = ["Nathan <11278700+nathansnellaert@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.3"
requests = "^2.32.3"
tenacity = "^9.0.0"
pandera = "^0.21.0"
pyarrow = "^18.1.0"
subsetsio = "^0.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
