name: Fetch Forex Rates

on:
  schedule:
    - cron: '15 17 * * 1-5' 
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  fetch-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: nathansnellaert/subsets-ghactions-template@v0.1
        with:
          run_command: poetry run python src/fetch_rates.py --start-date "2020-01-01"
          api_key: ${{ secrets.SUBSETS_API_KEY }}
          commit_after_run: true